services:
  mysql-db:
    image: mysql:8.1
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: documents_hub
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"   # host:container, avoids conflicts
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: .
    container_name: backend-app
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/documents_hub
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  mysql-data:
