apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: document-service
  template:
    metadata:
      labels:
        app: document-service
    spec:
      containers:
      - name: document-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
