apiVersion: v1
kind: Service
metadata:
  name: document-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
  selector:
    app: document-service
