version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: payments_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - demo_network

  app:
    build: ./backend
    container_name: springapp
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/payments_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root@123
    restart: always
    networks:
      - demo_network

  frontend:
    build: ./frontend   # path to your frontend Dockerfile
    container_name: frontendapp
    depends_on:
      - app
    ports:
      - "5173:5173"
    networks:
      - demo_network
    restart: always

volumes:
  db_data:

networks:
  demo_network:
    driver: bridge