apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: document-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/my-org/document-service'
    targetRevision: HEAD
    path: infra/helm/document-service
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
