name: Backend CI

on:
  push:
    paths:
      - 'InsuranceBackend/**'
  pull_request:
    paths:
      - 'InsuranceBackend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: cd InsuranceBackend && mvn clean package -DskipTests

      - name: Run tests
        run: cd InsuranceBackend && mvn test

      - name: Build Docker image
        run: docker build -t insurance-backend ./InsuranceBackend
