
name: CI-CD
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Build customer-service
        working-directory: services/customer-service
        run: mvn -B -DskipTests package
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push customer-service image
        uses: docker/build-push-action@v6
        with:
          context: ./services/customer-service
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/customer-service:0.0.1
